openapi: 3.0.0
info:
  title: "RP Flask REST API"
  description: "An API about people and notes"
  version: "1.0.0"

servers:
- url: "/api"

paths:
  /database:
    get:
      operationId: "src.models.database.get_table_value"
      tags:
        - "Test"
      summary: "Get values from database"
      responses:
        "200":
          description: "Successfully read from database"